# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mongoid_accountify"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Schneider"]
  s.date = "2012-09-05"
  s.email = "hiasinho@me.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "lib/mongoid/accountify.rb",
    "lib/mongoid/accountify/account.rb",
    "lib/mongoid/accountify/config.rb",
    "lib/mongoid/accountify/railtie.rb",
    "lib/mongoid/accountify/version.rb",
    "lib/mongoid_accountify.rb",
    "lib/tasks/mongoid_accountify_tasks.rake",
    "mongoid_accountify.gemspec"
  ]
  s.homepage = "https://github.com/hiasinho/mongoid_accountify"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Account related models within mongoid"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, ["~> 3.0.4"])
      s.add_development_dependency(%q<redcarpet>, ["~> 2.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<mongoid>, ["~> 3.0.4"])
      s.add_dependency(%q<redcarpet>, ["~> 2.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<mongoid>, ["~> 3.0.4"])
    s.add_dependency(%q<redcarpet>, ["~> 2.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

